on: 
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Verifies that we can talk to the vax
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run uname
        uses: rsponholtz/NetBSD-Vax-Action@draft
        with:
          path: /usr/src/sys/
          run: |
            make
